version: '3'

services:

  reverse-proxy-service:
    image: nginx:latest
    container_name: reverse-proxy-container
    depends_on:
      - weather-forecast-serbia-service
      - weather-forecast-england-service
    volumes:
      - ./../ReverseProxy/nginx.conf:/etc/nginx/nginx.conf
      - ./../ReverseProxy/reverse-proxy.conf.template:/etc/nginx/conf.d/reverse-proxy.conf.template
    environment:
      - PORT=${PORT_ENV}
    command: >
      /bin/bash -c "envsubst '$${PORT}' < /etc/nginx/conf.d/reverse-proxy.conf.template 
      > /etc/nginx/conf.d/default.conf && 
      nginx -g 'daemon off;'"
    ports:
      - 8080:80

  reverse-proxy-ex-service:
    image: openresty/openresty:1.21.4.1-0-bullseye-fat
    container_name: reverse-proxy-ex-container
    depends_on:
      - weather-forecast-serbia-service
      - weather-forecast-england-service
    volumes:
      - ./../ReverseProxy/nginx-ex.conf:/usr/local/openresty/nginx/conf/nginx.conf
    environment:
      - PORT=${PORT_ENV}
    ports:
      - 8082:80

  weather-forecast-serbia-service:
    image: weather-forecast-serbia-image
    container_name: weather-forecast-serbia-container
    build:
      context: ./../WeatherForecastSerbia
      args:
        - PORT=${PORT_ENV}
    restart: on-failure

  weather-forecast-england-service:
    image: weather-forecast-england-image
    container_name: weather-forecast-england-container
    build:
      context: ./../WeatherForecastEngland
      args:
        - PORT=${PORT_ENV}
    restart: on-failure
